# Generated by Django 5.1.15 on 2025-12-20 09:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        error_messages={
                            "unique": "A user with that email already exists."
                        },
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("VENDOR", "Vendor"),
                            ("CUSTOMER", "Customer"),
                        ],
                        db_index=True,
                        default="CUSTOMER",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this user has verified their email address.",
                        verbose_name="email verified",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("SHIPPING", "Shipping Address"),
                            ("BILLING", "Billing Address"),
                            ("BOTH", "Shipping & Billing"),
                        ],
                        default="SHIPPING",
                        max_length=20,
                        verbose_name="address type",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="full name"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=17, verbose_name="phone number"),
                ),
                (
                    "address_line1",
                    models.CharField(max_length=255, verbose_name="address line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "state_province",
                    models.CharField(max_length=100, verbose_name="state/province"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="postal code"),
                ),
                (
                    "country",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this address by default",
                        verbose_name="default address",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
                "db_table": "addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "CUSTOMER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="customer_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="customer_avatars/%Y/%m/",
                        verbose_name="profile picture",
                    ),
                ),
                (
                    "loyalty_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Points earned from purchases",
                        verbose_name="loyalty points",
                    ),
                ),
                (
                    "newsletter_subscribed",
                    models.BooleanField(
                        default=False, verbose_name="newsletter subscription"
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(default=0, verbose_name="total orders"),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="total amount spent",
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        default="USD",
                        help_text="ISO 4217 currency code",
                        max_length=3,
                        verbose_name="preferred currency",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="en",
                        help_text="Language code (e.g., en, fr, es)",
                        max_length=10,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "customer profile",
                "verbose_name_plural": "customer profiles",
                "db_table": "customer_profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["loyalty_points"], name="customer_pr_loyalty_16efdb_idx"
                    ),
                    models.Index(
                        fields=["total_orders"], name="customer_pr_total_o_bc4707_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "VENDOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="vendor_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="business name",
                    ),
                ),
                (
                    "business_description",
                    models.TextField(
                        blank=True,
                        help_text="Describe your business and the products you sell",
                        verbose_name="business description",
                    ),
                ),
                (
                    "business_registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Official business registration or tax ID",
                        max_length=100,
                        verbose_name="business registration number",
                    ),
                ),
                (
                    "business_email",
                    models.EmailField(
                        blank=True,
                        help_text="Official business contact email",
                        max_length=254,
                        verbose_name="business email",
                    ),
                ),
                (
                    "business_phone",
                    models.CharField(
                        blank=True, max_length=17, verbose_name="business phone"
                    ),
                ),
                (
                    "business_address",
                    models.TextField(blank=True, verbose_name="business address"),
                ),
                (
                    "business_city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "business_state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                (
                    "business_country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "business_postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vendor_logos/%Y/%m/",
                        verbose_name="business logo",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vendor_banners/%Y/%m/",
                        verbose_name="store banner",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="vendor status",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Platform commission percentage (0-100)",
                        max_digits=5,
                        verbose_name="commission rate",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="rejection reason"),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Lifetime sales amount",
                        max_digits=12,
                        verbose_name="total sales",
                    ),
                ),
                (
                    "total_products",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of approved products",
                        verbose_name="total products",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Display this vendor in featured sections",
                        verbose_name="featured vendor",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "ADMIN"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_vendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "vendor profile",
                "verbose_name_plural": "vendor profiles",
                "db_table": "vendor_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email", "role"], name="users_email_7645ab_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "role"], name="users_is_acti_930397_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["user", "is_default"], name="addresses_user_id_41b398_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["user", "address_type"], name="addresses_user_id_6859f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["country", "city"], name="addresses_country_b4375e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorprofile",
            index=models.Index(
                fields=["status", "is_featured"], name="vendor_prof_status_c2ae5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorprofile",
            index=models.Index(
                fields=["business_name"], name="vendor_prof_busines_fe6836_idx"
            ),
        ),
    ]
