# Generated by Django 5.1.15 on 2025-12-25 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PRODUCT_APPROVED', 'Product Approved'), ('PRODUCT_REJECTED', 'Product Rejected'), ('PRODUCT_LOW_STOCK', 'Low Stock Alert'), ('PRODUCT_OUT_OF_STOCK', 'Out of Stock'), ('ORDER_CREATED', 'Order Created'), ('ORDER_PAID', 'Order Paid'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('NEW_ORDER_ITEM', 'New Order Item for Vendor'), ('VENDOR_APPROVED', 'Vendor Account Approved'), ('VENDOR_REJECTED', 'Vendor Account Rejected'), ('PAYOUT_PROCESSED', 'Payout Processed'), ('PAYMENT_SUCCEEDED', 'Payment Succeeded'), ('PAYMENT_FAILED', 'Payment Failed'), ('REFUND_PROCESSED', 'Refund Processed'), ('NEW_REVIEW', 'New Product Review'), ('REVIEW_REPLY', 'Review Reply'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_REJECTED', 'Return Rejected'), ('WELCOME', 'Welcome Message'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('PASSWORD_CHANGED', 'Password Changed'), ('SECURITY_ALERT', 'Security Alert'), ('PROMOTION', 'Promotional Message'), ('NEWSLETTER', 'Newsletter')], db_index=True, max_length=50, unique=True, verbose_name='notification type')),
                ('name', models.CharField(help_text='Human-readable name for this template', max_length=255, verbose_name='template name')),
                ('subject_template', models.CharField(help_text='Subject line (can use template variables like {{order_number}})', max_length=500, verbose_name='subject template')),
                ('body_text_template', models.TextField(help_text='Plain text email body with template variables', verbose_name='plain text template')),
                ('body_html_template', models.TextField(blank=True, help_text='HTML email body with template variables', verbose_name='HTML template')),
                ('available_variables', models.JSONField(blank=True, default=list, help_text='List of variables that can be used in this template', verbose_name='available variables')),
                ('is_active', models.BooleanField(default=True, help_text='Use this template for notifications', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'db_table': 'email_templates',
                'ordering': ['notification_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user_id', models.IntegerField(db_index=True, help_text='User ID from auth-service', primary_key=True, serialize=False, verbose_name='user ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='email notifications enabled')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS notifications enabled')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='push notifications enabled')),
                ('order_notifications', models.BooleanField(default=True, help_text='Receive notifications about order updates', verbose_name='order notifications')),
                ('product_notifications', models.BooleanField(default=True, help_text='Receive notifications about product approvals/stock', verbose_name='product notifications')),
                ('payment_notifications', models.BooleanField(default=True, help_text='Receive notifications about payments/refunds', verbose_name='payment notifications')),
                ('shipping_notifications', models.BooleanField(default=True, help_text='Receive notifications about shipment updates', verbose_name='shipping notifications')),
                ('review_notifications', models.BooleanField(default=True, help_text='Receive notifications about product reviews', verbose_name='review notifications')),
                ('promotional_notifications', models.BooleanField(default=False, help_text='Receive promotional offers and deals', verbose_name='promotional notifications')),
                ('newsletter_enabled', models.BooleanField(default=False, help_text='Receive newsletter emails', verbose_name='newsletter enabled')),
                ('digest_enabled', models.BooleanField(default=False, help_text='Receive notifications as daily digest instead of real-time', verbose_name='digest mode')),
                ('digest_time', models.TimeField(blank=True, help_text='Time of day to send digest (e.g., 09:00)', null=True, verbose_name='digest time')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Disable notifications during certain hours', verbose_name='quiet hours enabled')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (e.g., 22:00)', null=True, verbose_name='quiet hours start')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours (e.g., 08:00)', null=True, verbose_name='quiet hours end')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('announcement_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('MAINTENANCE', 'Maintenance'), ('FEATURE', 'New Feature'), ('PROMOTION', 'Promotion')], default='INFO', max_length=20, verbose_name='type')),
                ('target_all_users', models.BooleanField(default=True, help_text='Show to all users', verbose_name='target all users')),
                ('target_admins', models.BooleanField(default=False, verbose_name='target admins')),
                ('target_vendors', models.BooleanField(default=False, verbose_name='target vendors')),
                ('target_customers', models.BooleanField(default=False, verbose_name='target customers')),
                ('is_active', models.BooleanField(default=True, help_text='Show this announcement', verbose_name='active')),
                ('is_dismissible', models.BooleanField(default=True, help_text='Users can dismiss this announcement', verbose_name='dismissible')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Higher priority shown first', verbose_name='priority')),
                ('valid_from', models.DateTimeField(verbose_name='valid from')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave blank for indefinite', null=True, verbose_name='valid until')),
                ('action_text', models.CharField(blank=True, help_text='Text for action button (e.g., "Learn More")', max_length=100, verbose_name='action button text')),
                ('action_url', models.CharField(blank=True, help_text='URL for action button', max_length=500, verbose_name='action URL')),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, help_text='Admin user ID from auth-service who created this announcement', null=True, verbose_name='created by user ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'system announcement',
                'verbose_name_plural': 'system announcements',
                'db_table': 'system_announcements',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='system_anno_is_acti_992ac6_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField(blank=True, db_index=True, help_text='User ID from auth-service who received this email', null=True, verbose_name='recipient user ID')),
                ('recipient_email', models.EmailField(db_index=True, help_text='Email address where notification was sent', max_length=254, verbose_name='recipient email')),
                ('notification_type', models.CharField(choices=[('PRODUCT_APPROVED', 'Product Approved'), ('PRODUCT_REJECTED', 'Product Rejected'), ('PRODUCT_LOW_STOCK', 'Low Stock Alert'), ('PRODUCT_OUT_OF_STOCK', 'Out of Stock'), ('ORDER_CREATED', 'Order Created'), ('ORDER_PAID', 'Order Paid'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('NEW_ORDER_ITEM', 'New Order Item for Vendor'), ('VENDOR_APPROVED', 'Vendor Account Approved'), ('VENDOR_REJECTED', 'Vendor Account Rejected'), ('PAYOUT_PROCESSED', 'Payout Processed'), ('PAYMENT_SUCCEEDED', 'Payment Succeeded'), ('PAYMENT_FAILED', 'Payment Failed'), ('REFUND_PROCESSED', 'Refund Processed'), ('NEW_REVIEW', 'New Product Review'), ('REVIEW_REPLY', 'Review Reply'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_REJECTED', 'Return Rejected'), ('WELCOME', 'Welcome Message'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('PASSWORD_CHANGED', 'Password Changed'), ('SECURITY_ALERT', 'Security Alert'), ('PROMOTION', 'Promotional Message'), ('NEWSLETTER', 'Newsletter')], db_index=True, max_length=50, verbose_name='notification type')),
                ('subject', models.CharField(max_length=500, verbose_name='email subject')),
                ('body_text', models.TextField(help_text='Plain text version of email', verbose_name='plain text body')),
                ('body_html', models.TextField(blank=True, help_text='HTML version of email', verbose_name='HTML body')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked')], db_index=True, default='PENDING', max_length=20, verbose_name='status')),
                ('provider_message_id', models.CharField(blank=True, help_text='Message ID from email service (e.g., SendGrid, AWS SES)', max_length=255, verbose_name='provider message ID')),
                ('error_message', models.TextField(blank=True, help_text='Error details if sending failed', verbose_name='error message')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='opened at')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='clicked at')),
                ('bounced_at', models.DateTimeField(blank=True, null=True, verbose_name='bounced at')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'email notification',
                'verbose_name_plural': 'email notifications',
                'db_table': 'email_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_email', '-created_at'], name='email_notif_recipie_f9cd08_idx'), models.Index(fields=['status', '-created_at'], name='email_notif_status_fac01b_idx'), models.Index(fields=['provider_message_id'], name='email_notif_provide_a38e3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField(db_index=True, help_text='User ID from auth-service who receives this notification', verbose_name='recipient user ID')),
                ('notification_type', models.CharField(choices=[('PRODUCT_APPROVED', 'Product Approved'), ('PRODUCT_REJECTED', 'Product Rejected'), ('PRODUCT_LOW_STOCK', 'Low Stock Alert'), ('PRODUCT_OUT_OF_STOCK', 'Out of Stock'), ('ORDER_CREATED', 'Order Created'), ('ORDER_PAID', 'Order Paid'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('NEW_ORDER_ITEM', 'New Order Item for Vendor'), ('VENDOR_APPROVED', 'Vendor Account Approved'), ('VENDOR_REJECTED', 'Vendor Account Rejected'), ('PAYOUT_PROCESSED', 'Payout Processed'), ('PAYMENT_SUCCEEDED', 'Payment Succeeded'), ('PAYMENT_FAILED', 'Payment Failed'), ('REFUND_PROCESSED', 'Refund Processed'), ('NEW_REVIEW', 'New Product Review'), ('REVIEW_REPLY', 'Review Reply'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_REJECTED', 'Return Rejected'), ('WELCOME', 'Welcome Message'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('PASSWORD_CHANGED', 'Password Changed'), ('SECURITY_ALERT', 'Security Alert'), ('PROMOTION', 'Promotional Message'), ('NEWSLETTER', 'Newsletter')], db_index=True, max_length=50, verbose_name='notification type')),
                ('title', models.CharField(help_text='Notification headline', max_length=255, verbose_name='title')),
                ('message', models.TextField(help_text='Notification body text', verbose_name='message')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500, verbose_name='action URL')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('is_important', models.BooleanField(default=False, help_text='Mark as high priority', verbose_name='important')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data as JSON', verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_id', 'is_read', '-created_at'], name='notificatio_recipie_dde14f_idx'), models.Index(fields=['recipient_id', 'notification_type'], name='notificatio_recipie_b1a229_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_3c688e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='User ID from auth-service', verbose_name='user ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True, verbose_name='dismissed at')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='notifications.systemannouncement')),
            ],
            options={
                'verbose_name': 'announcement dismissal',
                'verbose_name_plural': 'announcement dismissals',
                'db_table': 'announcement_dismissals',
                'indexes': [models.Index(fields=['user_id', 'announcement'], name='announcemen_user_id_533341_idx')],
                'unique_together': {('announcement', 'user_id')},
            },
        ),
    ]
