# Generated by Django 5.1.15 on 2025-12-25 02:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, help_text='Unique tracking number from carrier', max_length=255, unique=True, verbose_name='tracking number')),
                ('order_id', models.IntegerField(db_index=True, help_text='Order ID from order-service', verbose_name='order ID')),
                ('vendor_id', models.IntegerField(blank=True, db_index=True, help_text='Vendor user ID from auth-service responsible for this shipment', null=True, verbose_name='vendor ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY_TO_SHIP', 'Ready to Ship'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED_DELIVERY', 'Failed Delivery'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30, verbose_name='shipment status')),
                ('carrier_name', models.CharField(blank=True, help_text='e.g., DHL, FedEx, UPS', max_length=255, verbose_name='carrier name')),
                ('carrier_service', models.CharField(blank=True, help_text='e.g., "FedEx International Priority"', max_length=255, verbose_name='carrier service')),
                ('carrier_tracking_url', models.URLField(blank=True, help_text='Full URL to track shipment on carrier website', verbose_name='tracking URL')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='total weight (kg)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='length (cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='width (cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='height (cm)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, help_text='Actual shipping cost charged to customer', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='shipping cost')),
                ('carrier_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost charged by carrier (for profit calculation)', max_digits=12, null=True, verbose_name='carrier cost')),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='estimated delivery date')),
                ('shipping_address_snapshot', models.TextField(help_text='Full formatted shipping address as text', verbose_name='shipping address')),
                ('special_instructions', models.TextField(blank=True, help_text='Special handling instructions for carrier', verbose_name='special instructions')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='shipped at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Standard Shipping", "Express Delivery"', max_length=255, unique=True, verbose_name='shipping method name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('base_cost', models.DecimalField(decimal_places=2, help_text='Base shipping cost', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='base cost')),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional cost per kilogram', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='cost per kg')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order total for free shipping (null = no free shipping)', max_digits=12, null=True, verbose_name='free shipping threshold')),
                ('min_delivery_days', models.PositiveIntegerField(help_text='Estimated minimum days for delivery', verbose_name='minimum delivery days')),
                ('max_delivery_days', models.PositiveIntegerField(help_text='Estimated maximum days for delivery', verbose_name='maximum delivery days')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_international', models.BooleanField(default=True, help_text='Available for international orders?', verbose_name='international shipping')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'shipping method',
                'verbose_name_plural': 'shipping methods',
                'db_table': 'shipping_methods',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "North America", "European Union"', max_length=255, unique=True, verbose_name='zone name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('countries', models.TextField(help_text='Comma-separated ISO 3166-1 alpha-2 country codes (e.g., US,CA,MX)', verbose_name='country codes')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiply shipping cost by this value (e.g., 1.5 = +50%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price multiplier')),
                ('additional_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat fee added to shipping cost', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='additional fee')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'shipping zone',
                'verbose_name_plural': 'shipping zones',
                'db_table': 'shipping_zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='return number')),
                ('order_id', models.IntegerField(db_index=True, help_text='Order ID from order-service', verbose_name='order ID')),
                ('order_item_id', models.IntegerField(db_index=True, help_text='Order item ID from order-service (specific item being returned)', verbose_name='order item ID')),
                ('customer_id', models.IntegerField(db_index=True, help_text='Customer user ID from auth-service', verbose_name='customer ID')),
                ('vendor_id', models.IntegerField(db_index=True, help_text='Vendor user ID from auth-service', verbose_name='vendor ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SHIPPED', 'Shipped by Customer'), ('RECEIVED', 'Received by Vendor'), ('INSPECTED', 'Inspected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=20, verbose_name='return status')),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective/Damaged'), ('WRONG_ITEM', 'Wrong Item'), ('NOT_AS_DESCRIBED', 'Not as Described'), ('SIZE_ISSUE', 'Size/Fit Issue'), ('QUALITY_ISSUE', 'Quality Issue'), ('CHANGED_MIND', 'Changed Mind'), ('OTHER', 'Other')], max_length=20, verbose_name='return reason')),
                ('description', models.TextField(help_text='Customer explanation for return', verbose_name='description')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity to return')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='returns/%Y/%m/', verbose_name='image 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='returns/%Y/%m/', verbose_name='image 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='returns/%Y/%m/', verbose_name='image 3')),
                ('return_tracking_number', models.CharField(blank=True, help_text='Tracking number for return shipment', max_length=255, verbose_name='return tracking number')),
                ('return_carrier', models.CharField(blank=True, max_length=255, verbose_name='return carrier')),
                ('return_label_provided', models.BooleanField(default=False, help_text='Did vendor/platform provide prepaid return label?', verbose_name='return label provided')),
                ('resolution_note', models.TextField(blank=True, help_text='Vendor/admin notes on resolution', verbose_name='resolution note')),
                ('processed_by_id', models.IntegerField(blank=True, db_index=True, help_text='Vendor or admin user ID from auth-service who processed this', null=True, verbose_name='processed by user ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='received at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'return request',
                'verbose_name_plural': 'return requests',
                'db_table': 'return_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id', 'status'], name='return_requ_order_i_87f22d_idx'), models.Index(fields=['customer_id', '-created_at'], name='return_requ_custome_32a7d8_idx'), models.Index(fields=['vendor_id', 'status'], name='return_requ_vendor__1b5881_idx'), models.Index(fields=['return_number'], name='return_requ_return__517635_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShippingLabel',
            fields=[
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='label', serialize=False, to='shipping.shipment')),
                ('label_file', models.FileField(help_text='PDF or image file of shipping label', upload_to='shipping_labels/%Y/%m/', verbose_name='label file')),
                ('label_format', models.CharField(choices=[('PDF', 'PDF'), ('PNG', 'PNG'), ('ZPL', 'ZPL')], default='PDF', max_length=10, verbose_name='label format')),
                ('label_id', models.CharField(blank=True, help_text='Carrier-provided label ID', max_length=255, verbose_name='label ID')),
                ('rate_id', models.CharField(blank=True, help_text='Rate ID from carrier API', max_length=255, verbose_name='rate ID')),
                ('postage_cost', models.DecimalField(decimal_places=2, help_text='Cost of postage/label', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='postage cost')),
                ('barcode', models.CharField(blank=True, max_length=255, verbose_name='barcode')),
                ('is_voided', models.BooleanField(default=False, help_text='Has this label been voided?', verbose_name='voided')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='voided at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'shipping label',
                'verbose_name_plural': 'shipping labels',
                'db_table': 'shipping_labels',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.shippingmethod'),
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.IntegerField(db_index=True, help_text='Order item ID from order-service', verbose_name='order item ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of this item in shipment (can be partial)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.shipment')),
            ],
            options={
                'verbose_name': 'shipment item',
                'verbose_name_plural': 'shipment items',
                'db_table': 'shipment_items',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['shipment'], name='shipment_it_shipmen_e00b27_idx'), models.Index(fields=['order_item_id'], name='shipment_it_order_i_4a83cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Status at this tracking point', max_length=30, verbose_name='status')),
                ('location', models.CharField(blank=True, help_text='Current location of package', max_length=500, verbose_name='location')),
                ('description', models.TextField(blank=True, help_text='Detailed status description from carrier', verbose_name='description')),
                ('event_time', models.DateTimeField(help_text='When this tracking event occurred', verbose_name='event time')),
                ('carrier_status_code', models.CharField(blank=True, max_length=100, verbose_name='carrier status code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shipping.shipment')),
            ],
            options={
                'verbose_name': 'shipment tracking event',
                'verbose_name_plural': 'shipment tracking events',
                'db_table': 'shipment_tracking',
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['shipment', '-event_time'], name='shipment_tr_shipmen_ddbe3a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order_id', 'status'], name='shipments_order_i_1ac412_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['vendor_id', 'status'], name='shipments_vendor__1cc1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipments_trackin_cc256d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', '-created_at'], name='shipments_status_d355f8_idx'),
        ),
    ]
